### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by Lusitaniae** [geerlingguy/ansible-role-munin-node#13]
The installation of some packages depend on certain dependencies to be installed.

for instance, nginx_request plugin will fail to run with this error:

```
Use of uninitialized value $LWP::VERSION in sprintf at /etc/munin/plugins/nginx_request line 109.
Can't locate object method "new" via package "LWP::UserAgent" at /etc/munin/plugins/nginx_request line 109.
```

Which is usually fixed by installing
`libwww-perl`

Should we account for this on the role?

**Comment by geerlingguy** [comment]
@Lusitaniae - This role is meant to be a generic way to install and configure munin-node. There are dozens of different kinds of servers you might use this on, and in each case, the munin plugins require different libraries to be present.

The best way to account for those libraries is to install them in the playbook that calls this role, e.g.

```yaml
---
- hosts: web
  roles:
    - geerlingguy.nginx
    - geerlingguy.munin-node
  tasks:
    - apt: name=libwww-perl state=present
```

(or in a place like `pre-tasks` if it's needed before the role is installed).
