### ISSUE TITLE
Custom plugins are not copied

### ISSUE THREAD

**Issue by amedee** [geerlingguy/ansible-role-munin-node#27]
I have this in my `meta/main.yml`:

```yaml
  - role: geerlingguy.munin-node
    munin_node_allowed_ips:
      - '^127\.0\.0\.1$'
      - '^::1$'
      - '^IP_ADDRESS$'
    munin_node_config: {
      "backup_size": {
        "user": "root"
      },
      "mailbox_*": {
        "user": "root",
        "env.mailbox_user": "EMAIL"
      }
    }
    munin_node_install_plugins:
      - src: files/etc/munin/plugins/backup_size
      - src: files/etc/munin/plugins/mailbox_messages
      - src: files/etc/munin/plugins/mailbox_size

```

My custom plugin scripts are not installed. The config is correct, though.

I am going to assume that there is a simple error at my end, that I got something wrong in the syntax of `munin_node_install_plugins`. How do I fix this?

**Comment by amedee** [comment]
I could not get it to work, so I added this task in my role:

```yaml
- name: Install custom munin plugins
  ansible.builtin.copy:
    src: etc/munin/plugins/
    dest: /etc/munin/plugins/
    owner: root
    mode: u=rwx,go=rx
  notify: Restart munin-node
```
